# Development environment configuration

simulation:
  time_step: 0.1
  max_iterations: 1000
  random_seed: 123
  debug_mode: true
  verbose_logging: true

phenomena:
  cellular_networks:
    network_size: 100
    connectivity: 0.05
    update_frequency: 10
    
  molecular_noise:
    noise_amplitude: 0.05
    correlation_time: 0.5
    noise_type: "gaussian"
    
  genetic_circuits:
    circuit_complexity: 5
    mutation_rate: 0.005
    expression_levels: [0.1, 0.5, 1.0]

optimization:
  algorithm: "genetic"
  population_size: 50
  generations: 100
  elite_ratio: 0.1

resources:
  memory_limit: "4GB"
  cpu_cores: 4
  gpu_enabled: false

logging:
  level: "DEBUG"
  file: "biocomputing_dev.log"
  console_output: true
