# Production environment configuration

simulation:
  time_step: 0.01
  max_iterations: 100000
  random_seed: null  # Use system time
  debug_mode: false
  verbose_logging: false

phenomena:
  cellular_networks:
    network_size: 10000
    connectivity: 0.1
    update_frequency: 1
    
  molecular_noise:
    noise_amplitude: 0.1
    correlation_time: 1.0
    noise_type: "gaussian"
    
  genetic_circuits:
    circuit_complexity: 20
    mutation_rate: 0.001
    expression_levels: [0.05, 0.1, 0.2, 0.5, 1.0, 2.0]

optimization:
  algorithm: "evolutionary"
  population_size: 1000
  generations: 10000
  elite_ratio: 0.05

resources:
  memory_limit: "64GB"
  cpu_cores: 32
  gpu_enabled: true

logging:
  level: "INFO"
  file: "biocomputing_prod.log"
  console_output: false

performance:
  parallel_processing: true
  batch_size: 1000
  checkpoint_frequency: 1000
